services:
  registry:
    image: qdrant/qdrant:v1.16
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - registry-data:/data

  embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    platform: ${TEI_PLATFORM:-linux/amd64}
    ports:
      - "8081:80"
    volumes:
      - embedding-data:/data
    environment:
      - MODEL_ID=${TEI_EMBEDDING_MODEL_ID}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'

volumes:
  registry-data:
  embedding-data:
